Repository stolostron/search-ui, pull requests merged in 2021-05, with the labels that each got.

#140 added search name requirement indicator
  frontend/public/locales/en/search.json
  frontend/src/routes/SearchPage/components/Modals/SaveAndEditSearchModal.tsx
Labels: approved, lgtm

#141 update favicon
  frontend/public/favicon.svg
Labels: approved, lgtm

#144 remove copyright from xml
  frontend/public/favicon.svg
  frontend/public/index.html
  package-lock.json
  package.json
Labels: approved, do-not-merge/hold

#146 update fastify-csrf pkg
  backend/package-lock.json
  backend/package.json
Labels: approved, lgtm

#145 Added alert condition for search disablement
  frontend/public/locales/en/overview.json
  frontend/public/locales/en/search.json
  frontend/src/routes/Overview/OverviewPage.tsx
  frontend/src/routes/SearchPage/SearchPage.tsx
Labels: lgtm

#147 removed cancel action from help modal
  frontend/src/routes/SearchPage/components/Modals/SearchInfoModal.tsx
Labels: approved, lgtm

#149 Update package dependencies
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: approved, lgtm

#150 Revert "Adjusting application URL parameters."
  frontend/src/routes/SearchPage/__snapshots__/searchDefinitions.test.ts.snap
  frontend/src/routes/SearchPage/searchDefinitions.test.ts
  frontend/src/routes/SearchPage/searchDefinitions.tsx
Labels: lgtm

#151 Adjusting parameters and accounting for both apigroups.
  frontend/src/routes/SearchPage/__snapshots__/searchDefinitions.test.ts.snap
  frontend/src/routes/SearchPage/searchDefinitions.test.ts
  frontend/src/routes/SearchPage/searchDefinitions.tsx
Labels: lgtm

#148 Show scope in PolicyReport results table
  frontend/src/routes/SearchPage/__snapshots__/searchDefinitions.test.ts.snap
  frontend/src/routes/SearchPage/searchDefinitions.tsx
Labels: approved, do-not-merge/hold

#152 fix grafana link from overiew page
  frontend/src/routes/Overview/OverviewPage.tsx
Labels: approved, lgtm
