Repository stolostron/search-ui, pull requests merged in 2021-03, with the labels that each got.

#112 Update default protocol for local console-api
  frontend/src/console-sdk/console-sdk.yml
Labels: approved, lgtm

#113 Update dependencies (fastify-reply-from vulnerability)
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: approved, lgtm

#116 Add Install Target to Makefile.prow
  Makefile.prow
Labels: approved, lgtm

#117 Add build target to Makefile.prow
  Makefile.prow
Labels: approved, lgtm

#118 Use tabs in Makefile.prow
  Dockerfile.prow
  Makefile.prow
Labels: approved

#119 Fix Dockerimage build in prow
  Dockerfile
  Makefile.prow
Labels: approved, lgtm

#120 remove self link
  frontend/src/routes/Overview/OverviewPage.tsx
Labels: approved, do-not-merge/hold, lgtm
