Repository stolostron/search-ui, pull requests merged in 2021-06, with the labels that each got.

#153 fixed error in url
  frontend/src/routes/SearchPage/__snapshots__/searchDefinitions.test.ts.snap
  frontend/src/routes/SearchPage/searchDefinitions.tsx
Labels: approved, lgtm

#154 Insight overview chart
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/overview.json
  frontend/src/lib/resource-request.ts
  frontend/src/routes/DetailsPage/DetailsPage.tsx
  frontend/src/routes/DetailsPage/YAMLPage.tsx
  frontend/src/routes/Overview/OverviewPage.test.tsx
  frontend/src/routes/Overview/OverviewPage.tsx
  frontend/src/routes/SearchPage/SearchPage.tsx
  frontend/src/routes/SearchPage/__snapshots__/searchDefinitions.test.ts.snap
  frontend/src/routes/SearchPage/components/Modals/SearchInfoModal.tsx
  frontend/src/routes/SearchPage/search-helper.ts
  frontend/src/routes/SearchPage/searchDefinitions.test.ts
  frontend/src/routes/SearchPage/searchDefinitions.tsx
Labels: approved, lgtm

#155 Consistent errors on YAML page
  frontend/src/routes/DetailsPage/YAMLPage.tsx
Labels: approved, lgtm

#156 Update POlicyReport fields
  frontend/public/locales/en/overview.json
  frontend/src/routes/Overview/OverviewPage.test.tsx
  frontend/src/routes/Overview/OverviewPage.tsx
  frontend/src/routes/SearchPage/__snapshots__/searchDefinitions.test.ts.snap
  frontend/src/routes/SearchPage/searchDefinitions.test.ts
  frontend/src/routes/SearchPage/searchDefinitions.tsx
Labels: approved, do-not-merge/hold

#159 update icon for new search tab
  frontend/src/routes/SearchPage/SearchPage.tsx
Labels: approved, lgtm

#158 Update libraries to latest
  backend/package-lock.json
  backend/package.json
  backend/src/server.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/SearchPage/SearchPage.tsx
  package-lock.json
  package.json
Labels: approved

#161 Resolve warnings on test output
  frontend/src/routes/Overview/OverviewPage.test.tsx
Labels: approved, lgtm

#160 Update modals for consistency & update ui-components version
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/search.json
  frontend/src/routes/DetailsPage/YAMLPage.tsx
  frontend/src/routes/SearchPage/components/Modals/DeleteResourceModal.tsx
  frontend/src/routes/SearchPage/components/Modals/DeleteSearchModal.tsx
Labels: approved, lgtm

#157 Component for info alerts
  frontend/public/locales/en/search.json
  frontend/src/routes/SearchPage/SearchPage.test.tsx
  frontend/src/routes/SearchPage/SearchPage.tsx
  frontend/src/routes/SearchPage/components/HeaderWithNotification.test.tsx
  frontend/src/routes/SearchPage/components/HeaderWithNotification.tsx
  frontend/src/routes/SearchPage/components/__snapshots__/HeaderWithNotification.test.tsx.snap
  frontend/src/search-sdk/search-sdk.ts
  frontend/src/search-sdk/searchQueries.graphql
  sonar-project.properties
Labels: approved, lgtm

#162 Dont allow deletion of PolicyReport resources from search page
  frontend/src/routes/SearchPage/components/SearchResults.tsx
Labels: approved

#163 Update overview provider
  frontend/src/routes/Overview/OverviewPage.test.tsx
  frontend/src/routes/Overview/OverviewPage.tsx
Labels: approved, lgtm

#164 npm update packages
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  package-lock.json
Labels: approved, lgtm

#165 Upgrade ui-components for newest header changes
  frontend/package-lock.json
  frontend/package.json
Labels: approved, lgtm

#167 ui-components 0.179.0
  frontend/package-lock.json
  frontend/package.json
Labels: approved, lgtm

#166 Fix YAML editor cursor placement issue
  frontend/src/routes/DetailsPage/YAMLEditor.css
Labels: approved, lgtm
